version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: local-password

  adminer:
    image: adminer
    ports:
      - 8080:8080

  # Comment out while in local
  # server:
  #   build: ./src/server
  #   command: npm start
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./src/server:/usr/app/
  #     - /usr/app/node_modules
  #   depends_on:
  #     - db

  # # Comment out while in local
  # client:
  #   build: ./src/client
  #   command: npm start
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./src/client:/usr/app
  #     - /usr/app/node_modules
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - db
  #     - server
